// ═══════════════════════════════════════════════════════════════
// Grades — Initial Database Migration
// ═══════════════════════════════════════════════════════════════
// Creates the [Grades] schema and the [Grades].[Grades] table
// with an auto-increment PK, StudentId index (for lookups),
// CourseName with max length, Score as decimal(10,2), and
// optional Notes. No FK constraint on StudentId — it is a
// logical reference to the Students microservice's data.
// Generated by: dotnet ef migrations add initialMigration
// ═══════════════════════════════════════════════════════════════

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace StudentDockerPortalProject.Grade.Migrations
{
    /// <inheritdoc />
    public partial class initialMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "Grades");

            migrationBuilder.CreateTable(
                name: "Grades",
                schema: "Grades",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    StudentId = table.Column<int>(type: "int", nullable: false),
                    CourseName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Score = table.Column<decimal>(type: "decimal(10,2)", nullable: false),
                    GradeDate = table.Column<DateTime>(type: "date", nullable: false),
                    Notes = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Grades", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Grades_StudentId",
                schema: "Grades",
                table: "Grades",
                column: "StudentId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Grades",
                schema: "Grades");
        }
    }
}
