// ═══════════════════════════════════════════════════════════════
// Students — Initial Database Migration
// ═══════════════════════════════════════════════════════════════
// Creates the [Students] schema and the [Students].[Students]
// table with an auto-increment PK, column constraints, and a
// unique index on Email. EnrollmentDate defaults to GETDATE().
// Generated by: dotnet ef migrations add initialMigration
// ═══════════════════════════════════════════════════════════════

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace StudentDockerPortalProject.Students.Migrations
{
    /// <inheritdoc />
    public partial class initialMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "Students");

            migrationBuilder.CreateTable(
                name: "Students",
                schema: "Students",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FirstName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    LastName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Email = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    DateOfBirth = table.Column<DateTime>(type: "date", nullable: false),
                    EnrollmentDate = table.Column<DateTime>(type: "date", nullable: false, defaultValueSql: "getdate()")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Students", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Students_Email",
                schema: "Students",
                table: "Students",
                column: "Email",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Students",
                schema: "Students");
        }
    }
}
